kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvarsel
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbvarsel/veilarbvarsel:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 999999
    timeout: 99999
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 99999
    timeout: 99999
  replicas:
    min: 1
    max: 1
    cpuThreasholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 2056Mi
    requests:
      cpu: 200m
      memory: 1500Mi
  envFrom:
    - configmap: pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbvarsel
        mountPath: /var/run/secrets/nais.io/service_user
