kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvarsel
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pgk.github.com/navikt/veilarbvarsel/veilarbvarsel:{{version}}