server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: veilarbvarsel
    bootstrap-servers: ${KAFKA_BROKERS_URL}
    schema-registry: ${KAFKA_SCHEMAS_URL}
topics:
  dab:
    varsel: privat-fo-varsel-q1
  doknotifikasjon:
    beskjed: aapen-brukernotifikasjon-nyBeskjed-v1
    oppgave: aapen-brukernotifikasjon-nyOppgave-v1
    done: aapen-brukernotifikasjon-done-v1
application:
  systemUser: veilarbvarsel

