name: Dev
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: docker.pkg.github.com/${{ github.repository }}/veilarbvarsel
  PRINT_LAYOUT: true

jobs:
  test-build-push:
    name: Test, Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Artifacts
        run: gradle |
          build
          ls build/libs